LATENT_DIM = 256
FEATURE_MAPS = 64
IMAGE_HEIGHT = 48
IMAGE_WIDTH = 64
CHANNELS = 3

BATCH_SIZE = 512
NUM_EPOCHS = 2000
INITIAL_LR = 0.0002
MIN_LR = 1e-6
BETAS = (0.5, 0.999)
WEIGHT_DECAY = 0.0001

REAL_LABEL_VAL = 0.9
FAKE_LABEL_VAL = 0.0

RESULTS_PATH = "results"
IMAGES_PATH = f"{RESULTS_PATH}/dcgan_images"
CHECKPOINTS_PATH = f"{RESULTS_PATH}/dcgan_checkpoints"
LOSSES_CSV = f"{RESULTS_PATH}/dcgan_losses.csv"

CHECKPOINT_FREQ = 10
SAMPLE_FREQ = 1
LOG_FREQ = 1000

SCHEDULER_T_MAX = NUM_EPOCHS 